name: Tests & Coverage

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Cache cargo and build
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: llvm-tools-preview
    
    # Generate code coverage with llvm-cov
    - name: Install cargo-llvm-cov
      run: if ! command -v cargo-llvm-cov >/dev/null; then cargo install cargo-llvm-cov; fi
    
    - name: Run tests with coverage
      working-directory: ${{ github.workspace }}
      run: cargo llvm-cov --ignore-filename-regex pretty.rs --lcov --output-path lcov.info --workspace --all-features --no-fail-fast

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./lcov.info
        verbose: true
        slug: johnhringiv/NCC-Rust