name: Lint

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    
    - name: Cache cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - name: Check formatting
      run: cargo fmt --all -- --check
    
    - name: Run clippy
      run: cargo clippy --workspace --all-targets --all-features -- -D warnings
    
    - name: Install cargo-sort
      run: if ! command -v cargo-sort >/dev/null; then cargo install cargo-sort --locked --version ^1; fi
    
    - name: Check dependency ordering
      run: cargo sort --workspace --check
    
    - name: Install cargo-machete
      run: if ! command -v cargo-machete >/dev/null; then cargo install cargo-machete --locked; fi
    
    - name: Check for unused dependencies
      run: cargo machete --with-metadata