name: Tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Verify submodule checkout
      run: |
        if [ ! -d "writing-a-c-compiler-tests/tests" ]; then
          echo "Submodule not properly initialized, attempting to fix..."
          git submodule update --init --recursive
        fi
        ls -la writing-a-c-compiler-tests/
    
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Cache cargo and build
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - name: Build
      run: cargo build --release
    
    - name: Run tests
o      working-directory: ${{ github.workspace }}
      run: cargo test --workspace --all-features --no-fail-fast